security:
  password_hashers:
    App\Entity\User: "auto"
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      provider: app_user_provider
      stateless: true
      json_login:
        check_path: /login
        username_path: email
        password_path: password
      custom_authenticators:
        - App\Security\JwtAuthenticator
  access_control:
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/audio, roles: IS_AUTHENTICATED_FULLY }
