parameters:
  audio_upload_directory: "%kernel.project_dir%/var/uploads/private/audio"
  project_images_directory: "%kernel.project_dir%/var/uploads/private/project_images"
  issued_by: "%env(ISSUED_BY)%"
  permitted_for: "%env(PERMITTED_FOR)%"
  mailer_from: "%env(MAILER_FROM)%"
  jwt_secret: "%env(JWT_SECRET)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
  App\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]
